# Generated by Django 2.2 on 2021-01-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('ISNB', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('noofcopies', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pbid', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('catagery', models.CharField(max_length=100)),
                ('ad_login', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('SSN', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ISNB', models.CharField(max_length=100)),
                ('issue_date', models.CharField(max_length=100)),
                ('return_date', models.CharField(max_length=100)),
                ('fine', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lends_return',
            },
        ),
        migrations.CreateModel(
            name='PubDetails',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('pub_year', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('SSN', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=255)),
                ('L_name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('specified_task', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'staff_member',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('SSN', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=100)),
                ('L_name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('catagery', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('ad_login', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
