# Generated by Django 2.2 on 2021-01-18 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booksDetails',
            fields=[
                ('ISNB', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('noofcopies', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pbid', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('catagery', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='loansDetails',
            fields=[
                ('SSN', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ISNB', models.CharField(max_length=100)),
                ('issue_date', models.CharField(max_length=100)),
                ('return_date', models.CharField(max_length=100)),
                ('fine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pubsDetails',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('pub_year', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='staffsDetails',
            fields=[
                ('SSN', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=100)),
                ('L_name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('specified_task', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usersDetails',
            fields=[
                ('SSN', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=100)),
                ('L_name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('catagery', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookdetails',
            name='ad_login',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='ad_login',
        ),
        migrations.CreateModel(
            name='specificuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('complete', models.BooleanField()),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.specificuser')),
            ],
        ),
    ]
